/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hmjcalc;

import hmjcalc.objects.Person;
import java.util.*;
//will need to import API stuff here

/**
 *
 * @author Harrison, Alex
 */

/* === NOTES ===
 * jcboDuration may be changed to jsDuration (into a spinner), but we need to find a way to limit the number
 */
public class HMJGUI extends javax.swing.JFrame {
    private Person user = null;

    Locale usEnglish = Locale.forLanguageTag("en-US");
    Locale mxSpanish = Locale.forLanguageTag("es-MX");
    Locale chChinese = Locale.forLanguageTag("zh-CN");

    //String getdisplayLanguage(Locale usEnglish);
    /**
     * Creates new form HMJGUI
     */
    //the <Status> part requires LinqToTwitter
    //We will need a new API to get the Twitter information, since LinqToTwitter only works with C#
    //private List<Status> currentTweets;
    public HMJGUI() {
        initComponents();
        user = new Person();
        /*GetMostRecent20HomeTimeLine();
        jta5Oclock.setText(null);
        currentTweets.ForEach(tweet =>
        jta5Oclock.append(tweet.Text));*/
    }
    
    /*private void GetMostRecent20HomeTimeLine() {
            var twitterContext = new TwitterContext(authorizer);

            var tweets = from tweet in twitterContext.Status
                         where tweet.Type == StatusType.Home &&
                         tweet.Count == 20
                         select tweet;

            currentTweets = tweets.ToList();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jlSex = new javax.swing.JLabel();
        jlAge = new javax.swing.JLabel();
        jcboSex = new javax.swing.JComboBox<>();
        jlLanguage = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jsAge = new javax.swing.JSpinner();
        jlWeight = new javax.swing.JLabel();
        jsWeight = new javax.swing.JSpinner();
        jlDesired = new javax.swing.JLabel();
        jlDuration = new javax.swing.JLabel();
        jcboDuration = new javax.swing.JComboBox<>();
        jlTitle = new javax.swing.JLabel();
        jcboDesired = new javax.swing.JComboBox<>();
        jcboBar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jlBarInfo = new javax.swing.JLabel();
        jlBar = new javax.swing.JLabel();
        jlDrinks = new javax.swing.JLabel();
        jlAContent = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnClear = new javax.swing.JButton();
        jlHMSID = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaHMSID = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaAContent = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta5Oclock = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlSex.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlSex.setText("Sex: ");

        jlAge.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlAge.setText("Age: ");

        jcboSex.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jcboSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        jlLanguage.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlLanguage.setText("Language:");

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Spanish", "Chinese" }));

        jsAge.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jlWeight.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlWeight.setText("Weight: ");

        jsWeight.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N

        jlDesired.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlDesired.setText("Desired Level of Drunkenness: ");

        jlDuration.setText("Duration:");

        jcboDuration.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jcboDuration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".5", "1", "1.5", "2", "2.5", "3", "3.5", "4", "4.5", "5", "5.5", "6", "6.5", "7", "7.5", "8" }));

        jlTitle.setFont(new java.awt.Font("Verdana", 3, 36)); // NOI18N
        jlTitle.setText("How Many Jrinks?");

        jcboDesired.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jcboDesired.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - Social", "2 - Witty & Charming", "3 - Buzzed", "4 - Patriotic", "5 - Tipsy", "6 - Horny", "7 - Sloppy", "8 - Reckless ", "9 - Train Wreck", "10 - Dead" }));

        jcboBar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jcboBar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Harry's", "Brother's Bar & Grill", "Neon Cactus", "Hunters Pub", "The Pint", "Klondike Pub", "Nine Irish Brothers", "Stacked Pickle", "Echo Karaoke", "308 On State", "Scotty's Brewhouse", "Knickerbocker Saloon", "Black Sparrow", "Double Deuce Saloon", "Local Bar", "Sgt Preston's of the North", "RedSeven Bar & Grill", "Lafayette Brewing Company", "DT Kirby's", "Blind Pig" }));

        jLabel1.setText("It's 5 O'clock somewhere!");

        jlBarInfo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jlBarInfo.setText("Bar Info");

        jlBar.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlBar.setText("Bar:");

        jlDrinks.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlDrinks.setText("Popular Drinks and Drink Specials: ");

        jlAContent.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jlAContent.setText("Alcohol Content");
        jlAContent.setToolTipText("");

        jbtnSave.setText("Save");
        jbtnSave.setToolTipText("");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnClear.setText("Clear");
        jbtnClear.setToolTipText("");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jlHMSID.setText("How Many Should I Drink?");

        jtaHMSID.setColumns(20);
        jtaHMSID.setRows(5);
        jScrollPane1.setViewportView(jtaHMSID);

        jtaAContent.setColumns(20);
        jtaAContent.setRows(5);
        jScrollPane2.setViewportView(jtaAContent);

        jta5Oclock.setColumns(20);
        jta5Oclock.setRows(5);
        jScrollPane4.setViewportView(jta5Oclock);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlBarInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlTitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlDesired)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcboDesired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlDuration)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcboDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlWeight)
                                            .addComponent(jlAge))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jsAge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jsWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlSex)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcboSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(jlLanguage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlBar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcboBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDrinks)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlAContent, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnClear)
                                        .addGap(221, 221, 221))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbtnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlHMSID, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTitle)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSex)
                            .addComponent(jcboSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlLanguage)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlAge)
                            .addComponent(jsAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlWeight)
                            .addComponent(jsWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDesired)
                            .addComponent(jcboDesired, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDuration)
                            .addComponent(jcboDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlBarInfo)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBar)
                    .addComponent(jcboBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDrinks, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlAContent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtnSave)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnClear))
                        .addComponent(jlHMSID, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        Boolean isMale;
        if (jcboSex.getSelectedItem().toString().equals("Male")) { isMale = true; }
        else { isMale = false; }
        user.setSex(isMale);
        user.setAge((Integer)jsAge.getValue());
        user.setWeight((Integer)jsWeight.getValue());
        user.sethLD((Double)jcboDuration.getSelectedItem());
        user.setDDrunk((Integer)jcboDesired.getSelectedItem());
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        jcboSex.setSelectedItem("Male");
        jsAge.setValue(0);
        jsWeight.setValue(0);
        jcboDuration.setSelectedItem(0.5);
        jcboDesired.setSelectedItem("1 - Social");
    }//GEN-LAST:event_jbtnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HMJGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HMJGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HMJGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HMJGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HMJGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JComboBox<String> jcboBar;
    private javax.swing.JComboBox<String> jcboDesired;
    private javax.swing.JComboBox<String> jcboDuration;
    private javax.swing.JComboBox<String> jcboSex;
    private javax.swing.JLabel jlAContent;
    private javax.swing.JLabel jlAge;
    private javax.swing.JLabel jlBar;
    private javax.swing.JLabel jlBarInfo;
    private javax.swing.JLabel jlDesired;
    private javax.swing.JLabel jlDrinks;
    private javax.swing.JLabel jlDuration;
    private javax.swing.JButton jlHMSID;
    private javax.swing.JLabel jlLanguage;
    private javax.swing.JLabel jlSex;
    private javax.swing.JLabel jlTitle;
    private javax.swing.JLabel jlWeight;
    private javax.swing.JSpinner jsAge;
    private javax.swing.JSpinner jsWeight;
    private javax.swing.JTextArea jta5Oclock;
    private javax.swing.JTextArea jtaAContent;
    private javax.swing.JTextArea jtaHMSID;
    // End of variables declaration//GEN-END:variables
}
